services:
  app:
    build: ./serve
    restart: unless-stopped
    volumes:
      - ./app/LaGuildeDesSeigneurs:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=guilde_seigneurs
      - MYSQL_PASSWORD=Y7*Z3PZ9cBNz
      - MYSQL_DATABASE=guilde_seigneurs
  ui:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=mysql
